spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/BatchDb
    username: postgres
    password: 1357
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  batch:
    jdbc:
      initialize-schema: always

server:
  port: 8080